---
- name: Install xDebug
  sudo: yes
  apt: pkg=php-xdebug state=latest

- name: adds xDebug settings
  sudo: yes
  template: src=xdebug.tpl dest=/etc/php/7.2/apache2/conf.d/20-xdebug.ini
  notify: restart apache